version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - "5444:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0-beta.5
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  webapp:
    build: .
    restart: always
    ports:
      - "8000:80"
    depends_on:
        - "graphql-engine"
volumes:
  db_data:

# psql postgres://postgres:postgrespassword@localhost:5432/postgres